// Code generated by hertz generator.

package banner

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _productsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _bannersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addnewbannerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deltebannerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getallbannersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatebannerMw() []app.HandlerFunc {
	// your code...
	return nil
}
