// Code generated by Kitex v0.6.1. DO NOT EDIT.

package microuser

import (
	"context"
	common_rpc "git.zqbjj.top/pet/services/cmd/rpc/user/kitex_gen/common_rpc"
	micro_user "git.zqbjj.top/pet/services/cmd/rpc/user/kitex_gen/micro_user"
	user "git.zqbjj.top/pet/services/cmd/rpc/user/kitex_gen/user"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return microUserServiceInfo
}

var microUserServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "micro_user"
	handlerType := (*micro_user.MicroUser)(nil)
	methods := map[string]kitex.MethodInfo{
		"SendSmsViaAliyun":       kitex.NewMethodInfo(sendSmsViaAliyunHandler, newMicroUserSendSmsViaAliyunArgs, newMicroUserSendSmsViaAliyunResult, false),
		"FreezePatrolBeforeAuth": kitex.NewMethodInfo(freezePatrolBeforeAuthHandler, newMicroUserFreezePatrolBeforeAuthArgs, newMicroUserFreezePatrolBeforeAuthResult, false),
		"FreezePatrolAfterAuth":  kitex.NewMethodInfo(freezePatrolAfterAuthHandler, newMicroUserFreezePatrolAfterAuthArgs, newMicroUserFreezePatrolAfterAuthResult, false),
		"VerifySmsCode":          kitex.NewMethodInfo(verifySmsCodeHandler, newMicroUserVerifySmsCodeArgs, newMicroUserVerifySmsCodeResult, false),
		"VerifyUsernamePwd":      kitex.NewMethodInfo(verifyUsernamePwdHandler, newMicroUserVerifyUsernamePwdArgs, newMicroUserVerifyUsernamePwdResult, false),
		"VerifyEmailPwd":         kitex.NewMethodInfo(verifyEmailPwdHandler, newMicroUserVerifyEmailPwdArgs, newMicroUserVerifyEmailPwdResult, false),
		"FindUser":               kitex.NewMethodInfo(findUserHandler, newMicroUserFindUserArgs, newMicroUserFindUserResult, false),
		"QueryUsersWithFilter":   kitex.NewMethodInfo(queryUsersWithFilterHandler, newMicroUserQueryUsersWithFilterArgs, newMicroUserQueryUsersWithFilterResult, false),
		"UpdateUser":             kitex.NewMethodInfo(updateUserHandler, newMicroUserUpdateUserArgs, newMicroUserUpdateUserResult, false),
		"CreateUser":             kitex.NewMethodInfo(createUserHandler, newMicroUserCreateUserArgs, newMicroUserCreateUserResult, false),
		"DeleteUser":             kitex.NewMethodInfo(deleteUserHandler, newMicroUserDeleteUserArgs, newMicroUserDeleteUserResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "micro_user",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.6.1",
		Extra:           extra,
	}
	return svcInfo
}

func sendSmsViaAliyunHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*micro_user.MicroUserSendSmsViaAliyunArgs)
	realResult := result.(*micro_user.MicroUserSendSmsViaAliyunResult)
	success, err := handler.(micro_user.MicroUser).SendSmsViaAliyun(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMicroUserSendSmsViaAliyunArgs() interface{} {
	return micro_user.NewMicroUserSendSmsViaAliyunArgs()
}

func newMicroUserSendSmsViaAliyunResult() interface{} {
	return micro_user.NewMicroUserSendSmsViaAliyunResult()
}

func freezePatrolBeforeAuthHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*micro_user.MicroUserFreezePatrolBeforeAuthArgs)
	realResult := result.(*micro_user.MicroUserFreezePatrolBeforeAuthResult)
	success, err := handler.(micro_user.MicroUser).FreezePatrolBeforeAuth(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMicroUserFreezePatrolBeforeAuthArgs() interface{} {
	return micro_user.NewMicroUserFreezePatrolBeforeAuthArgs()
}

func newMicroUserFreezePatrolBeforeAuthResult() interface{} {
	return micro_user.NewMicroUserFreezePatrolBeforeAuthResult()
}

func freezePatrolAfterAuthHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*micro_user.MicroUserFreezePatrolAfterAuthArgs)
	realResult := result.(*micro_user.MicroUserFreezePatrolAfterAuthResult)
	success, err := handler.(micro_user.MicroUser).FreezePatrolAfterAuth(ctx, realArg.Id)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMicroUserFreezePatrolAfterAuthArgs() interface{} {
	return micro_user.NewMicroUserFreezePatrolAfterAuthArgs()
}

func newMicroUserFreezePatrolAfterAuthResult() interface{} {
	return micro_user.NewMicroUserFreezePatrolAfterAuthResult()
}

func verifySmsCodeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*micro_user.MicroUserVerifySmsCodeArgs)
	realResult := result.(*micro_user.MicroUserVerifySmsCodeResult)
	success, err := handler.(micro_user.MicroUser).VerifySmsCode(ctx, realArg.Mobile, realArg.SmsCode)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newMicroUserVerifySmsCodeArgs() interface{} {
	return micro_user.NewMicroUserVerifySmsCodeArgs()
}

func newMicroUserVerifySmsCodeResult() interface{} {
	return micro_user.NewMicroUserVerifySmsCodeResult()
}

func verifyUsernamePwdHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*micro_user.MicroUserVerifyUsernamePwdArgs)
	realResult := result.(*micro_user.MicroUserVerifyUsernamePwdResult)
	success, err := handler.(micro_user.MicroUser).VerifyUsernamePwd(ctx, realArg.Username, realArg.EntryPwd)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newMicroUserVerifyUsernamePwdArgs() interface{} {
	return micro_user.NewMicroUserVerifyUsernamePwdArgs()
}

func newMicroUserVerifyUsernamePwdResult() interface{} {
	return micro_user.NewMicroUserVerifyUsernamePwdResult()
}

func verifyEmailPwdHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*micro_user.MicroUserVerifyEmailPwdArgs)
	realResult := result.(*micro_user.MicroUserVerifyEmailPwdResult)
	success, err := handler.(micro_user.MicroUser).VerifyEmailPwd(ctx, realArg.Email, realArg.EntryPwd)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newMicroUserVerifyEmailPwdArgs() interface{} {
	return micro_user.NewMicroUserVerifyEmailPwdArgs()
}

func newMicroUserVerifyEmailPwdResult() interface{} {
	return micro_user.NewMicroUserVerifyEmailPwdResult()
}

func findUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*micro_user.MicroUserFindUserArgs)
	realResult := result.(*micro_user.MicroUserFindUserResult)
	success, err := handler.(micro_user.MicroUser).FindUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMicroUserFindUserArgs() interface{} {
	return micro_user.NewMicroUserFindUserArgs()
}

func newMicroUserFindUserResult() interface{} {
	return micro_user.NewMicroUserFindUserResult()
}

func queryUsersWithFilterHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*micro_user.MicroUserQueryUsersWithFilterArgs)
	realResult := result.(*micro_user.MicroUserQueryUsersWithFilterResult)
	success, err := handler.(micro_user.MicroUser).QueryUsersWithFilter(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMicroUserQueryUsersWithFilterArgs() interface{} {
	return micro_user.NewMicroUserQueryUsersWithFilterArgs()
}

func newMicroUserQueryUsersWithFilterResult() interface{} {
	return micro_user.NewMicroUserQueryUsersWithFilterResult()
}

func updateUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*micro_user.MicroUserUpdateUserArgs)
	realResult := result.(*micro_user.MicroUserUpdateUserResult)
	success, err := handler.(micro_user.MicroUser).UpdateUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMicroUserUpdateUserArgs() interface{} {
	return micro_user.NewMicroUserUpdateUserArgs()
}

func newMicroUserUpdateUserResult() interface{} {
	return micro_user.NewMicroUserUpdateUserResult()
}

func createUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*micro_user.MicroUserCreateUserArgs)
	realResult := result.(*micro_user.MicroUserCreateUserResult)
	success, err := handler.(micro_user.MicroUser).CreateUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMicroUserCreateUserArgs() interface{} {
	return micro_user.NewMicroUserCreateUserArgs()
}

func newMicroUserCreateUserResult() interface{} {
	return micro_user.NewMicroUserCreateUserResult()
}

func deleteUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*micro_user.MicroUserDeleteUserArgs)
	realResult := result.(*micro_user.MicroUserDeleteUserResult)
	success, err := handler.(micro_user.MicroUser).DeleteUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMicroUserDeleteUserArgs() interface{} {
	return micro_user.NewMicroUserDeleteUserArgs()
}

func newMicroUserDeleteUserResult() interface{} {
	return micro_user.NewMicroUserDeleteUserResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) SendSmsViaAliyun(ctx context.Context, req *micro_user.RpcSmsReq) (r *common_rpc.RpcEmpty, err error) {
	var _args micro_user.MicroUserSendSmsViaAliyunArgs
	_args.Req = req
	var _result micro_user.MicroUserSendSmsViaAliyunResult
	if err = p.c.Call(ctx, "SendSmsViaAliyun", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FreezePatrolBeforeAuth(ctx context.Context, req *micro_user.RpcFreezeReq) (r *micro_user.RpcFreezeResp, err error) {
	var _args micro_user.MicroUserFreezePatrolBeforeAuthArgs
	_args.Req = req
	var _result micro_user.MicroUserFreezePatrolBeforeAuthResult
	if err = p.c.Call(ctx, "FreezePatrolBeforeAuth", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FreezePatrolAfterAuth(ctx context.Context, id *common_rpc.RpcId) (r *micro_user.RpcFreezeResp, err error) {
	var _args micro_user.MicroUserFreezePatrolAfterAuthArgs
	_args.Id = id
	var _result micro_user.MicroUserFreezePatrolAfterAuthResult
	if err = p.c.Call(ctx, "FreezePatrolAfterAuth", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) VerifySmsCode(ctx context.Context, mobile string, smsCode string) (r bool, err error) {
	var _args micro_user.MicroUserVerifySmsCodeArgs
	_args.Mobile = mobile
	_args.SmsCode = smsCode
	var _result micro_user.MicroUserVerifySmsCodeResult
	if err = p.c.Call(ctx, "VerifySmsCode", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) VerifyUsernamePwd(ctx context.Context, username string, entryPwd string) (r bool, err error) {
	var _args micro_user.MicroUserVerifyUsernamePwdArgs
	_args.Username = username
	_args.EntryPwd = entryPwd
	var _result micro_user.MicroUserVerifyUsernamePwdResult
	if err = p.c.Call(ctx, "VerifyUsernamePwd", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) VerifyEmailPwd(ctx context.Context, email string, entryPwd string) (r bool, err error) {
	var _args micro_user.MicroUserVerifyEmailPwdArgs
	_args.Email = email
	_args.EntryPwd = entryPwd
	var _result micro_user.MicroUserVerifyEmailPwdResult
	if err = p.c.Call(ctx, "VerifyEmailPwd", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FindUser(ctx context.Context, req *common_rpc.RpcId) (r *user.UserInfo, err error) {
	var _args micro_user.MicroUserFindUserArgs
	_args.Req = req
	var _result micro_user.MicroUserFindUserResult
	if err = p.c.Call(ctx, "FindUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) QueryUsersWithFilter(ctx context.Context, req *micro_user.RpcUsersFilterReq) (r []*user.UserInfo, err error) {
	var _args micro_user.MicroUserQueryUsersWithFilterArgs
	_args.Req = req
	var _result micro_user.MicroUserQueryUsersWithFilterResult
	if err = p.c.Call(ctx, "QueryUsersWithFilter", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateUser(ctx context.Context, req *user.UserInfo) (r *user.UserInfo, err error) {
	var _args micro_user.MicroUserUpdateUserArgs
	_args.Req = req
	var _result micro_user.MicroUserUpdateUserResult
	if err = p.c.Call(ctx, "UpdateUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateUser(ctx context.Context, req *user.UserInfo) (r *user.UserInfo, err error) {
	var _args micro_user.MicroUserCreateUserArgs
	_args.Req = req
	var _result micro_user.MicroUserCreateUserResult
	if err = p.c.Call(ctx, "CreateUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteUser(ctx context.Context, req *common_rpc.RpcId) (r *common_rpc.RpcEmpty, err error) {
	var _args micro_user.MicroUserDeleteUserArgs
	_args.Req = req
	var _result micro_user.MicroUserDeleteUserResult
	if err = p.c.Call(ctx, "DeleteUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
