// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	alert "git.zqbjj.top/pet/services/cmd/http/router/alert"
	"git.zqbjj.top/pet/services/cmd/http/router/auth"
	device "git.zqbjj.top/pet/services/cmd/http/router/device"

	"git.zqbjj.top/pet/services/cmd/http/router/user"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	alert.Register(r)

	device.Register(r)

	user.Register(r)

	auth.Register(r)

}
