// Code generated by Kitex v0.6.1. DO NOT EDIT.

package device

import (
	"context"
	common "git.zqbjj.top/pet/services/cmd/http/kitex_gen/common"
	device "git.zqbjj.top/pet/services/cmd/http/kitex_gen/device"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetDeviceList(ctx context.Context, req *device.DeviceFilter, callOptions ...callopt.Option) (r []*device.DeviceInfo, err error)
	GetDeviceDetail(ctx context.Context, req *common.Req, callOptions ...callopt.Option) (r *device.DeviceInfo, err error)
	UpdateDeviceInfo(ctx context.Context, req *device.DeviceInfo, callOptions ...callopt.Option) (r *device.DeviceInfo, err error)
	BindDevice(ctx context.Context, req *device.DeviceInfo, callOptions ...callopt.Option) (r *device.DeviceInfo, err error)
	UnbindDevice(ctx context.Context, req *common.Req, callOptions ...callopt.Option) (r *common.Empty, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kDeviceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kDeviceClient struct {
	*kClient
}

func (p *kDeviceClient) GetDeviceList(ctx context.Context, req *device.DeviceFilter, callOptions ...callopt.Option) (r []*device.DeviceInfo, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetDeviceList(ctx, req)
}

func (p *kDeviceClient) GetDeviceDetail(ctx context.Context, req *common.Req, callOptions ...callopt.Option) (r *device.DeviceInfo, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetDeviceDetail(ctx, req)
}

func (p *kDeviceClient) UpdateDeviceInfo(ctx context.Context, req *device.DeviceInfo, callOptions ...callopt.Option) (r *device.DeviceInfo, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateDeviceInfo(ctx, req)
}

func (p *kDeviceClient) BindDevice(ctx context.Context, req *device.DeviceInfo, callOptions ...callopt.Option) (r *device.DeviceInfo, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BindDevice(ctx, req)
}

func (p *kDeviceClient) UnbindDevice(ctx context.Context, req *common.Req, callOptions ...callopt.Option) (r *common.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UnbindDevice(ctx, req)
}
