// Code generated by Kitex v0.8.0. DO NOT EDIT.
package model

import (
	model "git.zqbjj.top/pet/services/cmd/rpc/product/kitex_gen/model"
	server "github.com/cloudwego/kitex/server"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler model.Model, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
